# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('image_lock', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('edit_set', 'Edit set'), ('delete_set', 'Delete set'), ('edit_annotation', 'Edit annotations in the set'), ('delete_annotation', 'Delete annotations in the set'), ('annotate', 'Create annotations in the set'), ('read', 'Read and download annotations and images'), ('create_export', 'Create export files of the set'), ('delete_export', 'Delete export files of the set')),
            },
        ),
    ]
