# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_export_export_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='validation',
            field=models.IntegerField(default=0),
        ),
    ]
