# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0006_annotation_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='validation',
        ),
        migrations.AddField(
            model_name='verification',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Annotation'),
        ),
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='verified_by',
            field=models.ManyToManyField(through='images.Verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
