# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20170830_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='users.Team'),
        ),
    ]
