# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20170219_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='verified',
            field=models.BooleanField(default=0),
        ),
    ]
