# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_verification_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='not_in_image',
            field=models.BooleanField(default=0),
        ),
    ]
