# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('images', '0009_annotation_not_in_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
