# Generated by Django 2.0.4 on 2018-05-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', 'export_format_conversion_20180504'),
        ('images', '0010_imageset_public_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='main_annotation_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotations.AnnotationType'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (0, 'Normal'), (-1, 'Low')], default=0),
        ),
    ]
