# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20170522_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageset',
            options={'permissions': (('edit_set', 'Edit set'), ('delete_set', 'Delete set'), ('edit_annotation', 'Edit annotations in the set'), ('delete_annotion', 'Delete annotations in the set'), ('annotate', 'Create annotations in the set'), ('read', 'Read and download annotations and images'))},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('user_management', 'Manage users'), ('create_set', 'Create imagesets'))},
        ),
    ]
