# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20170531_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='error', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageset',
            name='path',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
