# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20170623_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageset',
            options={'permissions': (('edit_set', 'Edit set'), ('delete_set', 'Delete set'), ('edit_annotation', 'Edit annotations in the set'), ('delete_annotation', 'Delete annotations in the set'), ('annotate', 'Create annotations in the set'), ('read', 'Read and download annotations and images'), ('create_export', 'Create export files of the set'), ('delete_export', 'Delete export files of the set'))},
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
