# Generated by Django 2.0.7 on 2018-07-10 22:30

from django.db import migrations


def set_test_tag(apps, schema_editor):
    SetTag = apps.get_model('images', 'SetTag')
    if SetTag.objects.filter(name='test').exists():
        test_tag = SetTag.objects.get(name='test')
    else:
        test_tag = SetTag(name='test')
        test_tag.save()

    ImageSet = apps.get_model('images', 'ImageSet')
    for imageset in ImageSet.objects.all():
        if 'test' in imageset.name.lower():
            test_tag.imagesets.add(imageset)

    test_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_imageset_pinned_by'),
    ]

    operations = [
        migrations.RunPython(set_test_tag)
    ]
