# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20170623_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='imageset',
            name='image_lock',
            field=models.BooleanField(default=False),
        ),
    ]
