# Generated by Django 2.0.9 on 2018-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_settag_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='zip_state',
            field=models.IntegerField(choices=[(0, 'invalid'), (1, 'ready'), (2, 'processing')], default=0),
        ),
    ]
