# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_auto_20170702_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='checksum',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
