version: '3'

services:
  db:
    environment:
      POSTGRES_DB: imagetagger
      POSTGRES_USER: imagetagger
      POSTGRES_PASSWORD: imagetagger
    # restart: always
    image: postgres:9.5
  web:
    environment:
      DATABASE_URL: postgres://imagetagger:imagetagger@db/imagetagger
    build: .
    command: python3 /imagetagger/imagetagger/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/imagetagger
    ports:
      - "8080:8080"
    depends_on:
      - db
