# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
