# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20170125_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='export_text',
            field=models.TextField(default=''),
        ),
    ]
