# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('images', '0010_auto_20170519_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='auth.Group')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='imageset',
            name='group',
        ),
        migrations.AddField(
            model_name='imageset',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Team'),
        ),
    ]
