# Generated by Django 2.0.9 on 2019-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(through='users.TeamMembership', to='users.Team'),
        ),
    ]
