# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170824_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
