# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Team'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImageSet'),
        ),
    ]
