# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20170825_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=800),
        ),
    ]
