# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20171120_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sets', to='users.Team'),
        ),
    ]
