# Generated by Django 2.0.4 on 2018-06-29 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0014_auto_20180629_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
