#!/bin/bash
set -e

runuser -u www-data -- /app/src/imagetagger/manage.py collectstatic --no-input
runuser -u www-data -- /app/src/imagetagger/manage.py migrate

nginx
exec uwsgi /etc/uwsgi/imagetagger.ini

