# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
