# Generated by Django 2.0.4 on 2018-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', 'export_format_conversion_20180504'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='_blurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='_concealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='enable_blurred',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='enable_concealed',
            field=models.BooleanField(default=True),
        ),
    ]
