# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='image_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImageSet'),
        ),
        migrations.AddField(
            model_name='export',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.AnnotationType'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='verified_by',
            field=models.ManyToManyField(through='annotations.Verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
