# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0003_auto_20170826_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together=set([('annotation', 'user')]),
        ),
    ]
