# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 12:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_auto_20170826_1431'),
    ]

    # This migration completes the previous data migration to JSONB

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='vector',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=False),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='raw_vector',
        ),
    ]
