# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_auto_20170828_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='export_type',
        ),
    ]
