# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0012_exportformat_not_in_image_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='min_verifications',
            field=models.IntegerField(default=0),
        ),
    ]
