# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0013_exportformat_min_verifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='annotations.ExportFormat'),
        ),
    ]
