# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0014_auto_20170907_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='image_aggregation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportformat',
            name='image_format',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
