# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0017_auto_20171220_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportformat',
            name='name_format',
            field=models.CharField(default='export_%%exportid.txt', max_length=200),
        ),
    ]
