# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0023_auto_20180428_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='annotations.ExportFormat'),
        ),
    ]
