# Generated by Django 2.0.7 on 2018-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0026_index_verification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='md_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
