# Generated by Django 2.0.4 on 2018-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_auto_20180508_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='include_blurred',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exportformat',
            name='include_concealed',
            field=models.BooleanField(default=True),
        ),
    ]
