# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0011_remove_export_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='not_in_image_format',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
