# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 08:22
from __future__ import unicode_literals

from django.db import migrations
import imagetagger.annotations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0018_auto_20171220_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportformat',
            name='annotation_format',
            field=imagetagger.annotations.fields.NonStrippingTextField(),
        ),
        migrations.AlterField(
            model_name='exportformat',
            name='base_format',
            field=imagetagger.annotations.fields.NonStrippingTextField(),
        ),
        migrations.AlterField(
            model_name='exportformat',
            name='image_format',
            field=imagetagger.annotations.fields.NonStrippingTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exportformat',
            name='not_in_image_format',
            field=imagetagger.annotations.fields.NonStrippingTextField(),
        ),
    ]
