# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import imagetagger.annotations.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0019_auto_20180314_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='node_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='vector_type',
            field=models.IntegerField(default=1),
        ),
    ]
