# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0022_auto_20180425_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='last_change_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 4, 28, 12, 0, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
