# Generated by Django 2.0.6 on 2018-06-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0025_points_trigger'),
    ]

    operations = [
        migrations.RunSQL('''
        CREATE INDEX annotations_verification_time ON annotations_verification(time)
        '''),
    ]
