# Generated by Django 2.0.7 on 2018-11-14 09:58

from django.db import migrations
import imagetagger.annotations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0026_index_verification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportformat',
            name='vector_format',
            field=imagetagger.annotations.fields.NonStrippingTextField(default='x%%count1: %%x%%bry%%count1: %%y%%br'),
        ),
    ]
