# Generated by Django 3.2.7 on 2021-09-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0027_auto_20181114_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='vector',
            field=models.JSONField(null=True),
        ),
    ]
